name: Flutter_charts
description: Flutter Charts is to create cartesian and circular charts.
version: 17.4.50

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    git: https://github.com/sad1996/charts_flutter_core
  intl: ">=0.15.0 <0.17.0"
  vector_math: ^2.0.8

flutter:
 